version: '3.9'

services:

  db:
    image: postgres:15
    container_name: odoo19-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  odoo:
    image: odoo:19.0
    container_name: odoo19-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-patches/translate.py:/usr/lib/python3/dist-packages/odoo/tools/translate.py:ro
      - ./custom_addons:/mnt/extra-addons
    restart: always